# Generated by Django 3.2.7 on 2021-11-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin_code',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
