# Generated by Django 3.0.14 on 2021-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
    ]
