# Generated by Django 3.0.14 on 2021-11-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20211111_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Title', models.CharField(max_length=200, null=True)),
                ('Brand_logo', models.ImageField(upload_to='Orders/Images')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('Product_Image', models.ImageField(blank=True, upload_to='Product/Images')),
                ('Price_Product', models.PositiveIntegerField(null=True)),
                ('Description', models.TextField(null=True)),
                ('Item_quality', models.CharField(choices=[('First Hand', 'First Hand'), ('Second Hand', 'Second Hand')], max_length=100, null=True)),
                ('Brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Ordered', 'Ordered'), ('Order_confirmed', 'Order_confirmed'), ('Out for delivery', 'Out for delivery'), ('Order Recieved', 'Order Recieved'), ('Order Reject', 'Order Reject')], max_length=200)),
                ('quantity', models.IntegerField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
