# Generated by Django 3.2.7 on 2021-11-20 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20211116_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='paid_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('order_confirmed', 'order_confirmed'), ('out for delivery', 'out for delivery'), ('Order Recieved', 'Order Recieved'), ('Order Reject', 'Order Reject')], max_length=200, null=True),
        ),
    ]
