# Generated by Django 3.2.7 on 2021-11-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20211120_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_No', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('Image', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.orders')),
            ],
        ),
    ]
