# Generated by Django 3.2.7 on 2021-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_cartorderitems_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('order_confirmed', 'order_confirmed'), ('out for delivery', 'out for delivery'), ('Order Recieved', 'Order Recieved'), ('Order Reject', 'Order Reject')], default='ordered', max_length=200, null=True),
        ),
    ]
