# Generated by Django 3.2.7 on 2021-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_productreviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewed',
            name='review_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=150),
        ),
    ]
