# Generated by Django 3.0.14 on 2021-11-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('DesktopType', models.CharField(max_length=200)),
                ('Problem', models.TextField(blank=True, null=True)),
                ('Submit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('Submit_month', models.CharField(blank=True, max_length=100, null=True)),
                ('Submit_year', models.CharField(blank=True, max_length=100, null=True)),
                ('return_date', models.CharField(blank=True, max_length=100, null=True)),
                ('return_month', models.CharField(blank=True, max_length=100, null=True)),
                ('return_year', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
                ('residual_amount', models.IntegerField(blank=True, null=True)),
                ('is_fullyPaid', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.CustomerModel')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ReferenceModel')),
            ],
        ),
    ]
