# Generated by Django 3.2.7 on 2021-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='DesktopCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='Brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='DesktopType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
