# Generated by Django 3.0.14 on 2021-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211111_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
