# Generated by Django 3.0.14 on 2021-11-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
        ('services', '0002_auto_20211115_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineshopsale',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
    ]
